DROP TABLE IF EXISTS GSUser;
DROP TABLE IF EXISTS User;

CREATE TABLE User (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role INT NOT NULL
);

CREATE TABLE GSUser (
	id INT AUTO_INCREMENT PRIMARY KEY,
	userid INT NOT NULL,
	uuid VARCHAR(10) NOT NULL,
	world_level int,
	FOREIGN KEY (userid) REFERENCES User(id)
);